name: Alpha Vantage Official
description: Official Alpha Vantage Adapter
node_identifier: alpha_vantage_cl_ea
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: Alpha Vantage
    url: https://alphavantage.co
parameters:
  - function
  - interval
  - symbol
  - outputsize
  - datatype
  - keywords
  - from_currency
  - to_currency
  - from_symbol
  - to_symbol
  - market
  - time_period
  - series_type
  - fast_limit
  - slow_limit
  - fastperiod
  - slowperiod
  - signalperiod
  - fastmatype
  - slowmatype
  - signalmatype
  - fastkperiod
  - slowkperiod
  - slowdperiod
  - slowkmatype
  - slowdmatype
  - fastdperiod
  - fastdmatype
  - fastdperiod
  - fastdmatype
  - matype
  - fast_period
  - slow_period
  - timeperiod1
  - timeperiod2
  - timeperiod3
  - nbdevup
  - nbdevdn
  - acceleration
  - maximum
